apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android 
{
  compileOptions 
  {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  compileSdkVersion 29
  namespace 'com.stupidbeauty.appstore.core'

  defaultConfig 
  {
    buildToolsVersion = "30.0.3"
    minSdkVersion 21
    targetSdkVersion 29
    versionCode 14164
  }

  buildTypes 
  {
    release 
    {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      multiDexKeepFile file('multidex-config.txt')
    }

    debug
    {
      minifyEnabled false
      shrinkResources false

      multiDexKeepFile file('multidex-config.txt')
      multiDexKeepProguard file('multidex-config.pro')
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }

  sourceSets {
      main {
          jniLibs.srcDirs=['libs']

          java.srcDirs = [ 'src/main/java' ]
      }
  }
    
  publishing
  {
    singleVariant('release')
    {
      withSourcesJar()
    }
  }

  return void
}

dependencies {
  implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
  implementation 'com.upokecenter:cbor:4.4.4'
  implementation 'com.rabbitmq:amqp-client:3.6.3'
  implementation fileTree(include: ['*.aar'], dir: 'libs')
  implementation 'com.github.hxcan:rotatingactiveuser:2021.11.29'
  coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
  
  implementation 'androidx.annotation:annotation:1.6.0' // Use the latest version available
}

afterEvaluate 
{
  publishing 
  {
    publications
    {
      release(MavenPublication)
      {
        from components.release
        groupId = 'com.github.hxcan'
        artifactId = 'appstore-core'
        version = '2024.8.22'
      }
    }
  }
}

