#ABNF 1.0 UTF-8;
language zh-CN;
tag-format <semantics/1.0>;

mode voice;

root $main;

$game = 比赛 ;

$team = 主队 | 客队 ;

$num = 一|二|三|四|五|六|七|八|九;
$ten = 十;


$player= ( $num | $ten  | ( $ten $num ) | ( $num $ten ) | ( $num $ten $num  ) ) 号   ; //球员号码。

$operation = 开始 | 结束 | 暂停 | 重新开始 | 终止 ;

$scoreModify = 增加 | 减少 ;

$scoreDelta = 一分 | 两分 | 三分 ;

$teamOperation = 换人 ;

$tacticsAction = $tacticsActionSimple | $tacticsActionComplex ;

$tacticsActionSimple = 乌龙 | 角球 | 任意球 | 助攻 | 越位 |  点球进球 | 点球未进 | 点球射正 | 点球 | 射门进球 | 射门未射正 | 射门射正 | 射门 ;

$tacticsActionComplex = $tacticsActionBetweenPeople | $tacticsActionPenalty ;

$tacticsActionBetweenPeople = ( 拦截 | 抢断 | 传球  ) [ $player ] ;

$tacticsActionPenalty =  犯规  [ $classifiedPenalty  [ $player ]  ] ;

$classifiedPenalty = 黄牌 | 红牌 | 警告 ;


$resultAction = 战胜 | 险胜 | 大胜 | 大败 | 惜败 ;

$main = ( $game $operation ) | ( $team ( ( $scoreModify $scoreDelta ) | $teamOperation    | ( $player $tacticsAction ) | ( $resultAction $team ) ) ) ;
